# Generated by Django 3.2.16 on 2023-08-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_in_hrs', models.FloatField(blank=True, null=True)),
                ('min_staff_required', models.IntegerField(blank=True, null=True)),
                ('max_staff_allowed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shift',
            },
        ),
    ]
