# Generated by Django 3.2.16 on 2023-07-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('divorced', 'Divorced')], default='unmarried', max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=employee.models.image_upload_to)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('shareReferralCode', models.CharField(blank=True, default=employee.models.create_empolyee_code, help_text="User's own referral code", max_length=20, null=True)),
                ('usedReferralCode', models.CharField(blank=True, help_text='code used while registration', max_length=20, null=True)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('active_inactive_date', models.DateField(blank=True, null=True)),
                ('reporting_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_person', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='user.userrole')),
            ],
            options={
                'db_table': 'employee_profile',
            },
        ),
    ]
