# Generated by Django 3.2.16 on 2023-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='shareReferralCode',
            field=models.CharField(blank=True, help_text="User's own referral code", max_length=20, null=True),
        ),
    ]
