# Generated by Django 3.2.16 on 2023-07-31 07:29

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeprofile_sharereferralcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=employee.models.image_upload_to)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('age_in_yrs', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
            options={
                'db_table': 'family_profile',
            },
        ),
    ]
