# Generated by Django 3.2.16 on 2023-08-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('employee', '0004_alter_familyprofile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_team_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
