# Generated by Django 3.2.16 on 2023-08-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permission_name', models.CharField(max_length=30, unique=True)),
                ('permission_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_permission',
            },
        ),
    ]
