# Generated by Django 3.2.16 on 2023-08-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_auto_20230801_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('attendance_time', models.TimeField(blank=True, null=True)),
                ('attendance', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('pending', 'Pending')], default='pending', max_length=20, null=True)),
                ('first_half', models.BooleanField(default=False)),
                ('second_half', models.BooleanField(default=False)),
                ('is_attendance_done', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
